### ISSUE TITLE
Occasional Graphical Corruption

### ISSUE THREAD

**Issue by rothn** [projectM-visualizer/frontend-sdl2#18] opened 2022-02-19 08:30 UTC
Sometimes the screen displays static-y graphical corruption.

Versions:
libprojectm: latest master (9e9f4ca1b2b767e7e35db60907b2868b096973b6)
frontend-sdl2: latest master (8200b32ba186dbfac1c7ca8d3c19c37cac5ce049)

Expected Behavior:
Normal Visualizations consistently

Actual Behavior:
Rapidly flickering seizure screen after some transitions
![Screenshot from 2022-02-19 02-18-33](https://user-images.githubusercontent.com/4665783/154793034-0de103d4-daa7-4546-9e18-49a6898c81f7.png)

Libraries:
https://github.com/libsdl-org/SDL/tree/release-2.0.20, installed with CMake
https://github.com/pocoproject/poco/tree/poco-1.11.1, installed with CMake
Otherwise, fully updated stock Ubuntu 21.10 as of filing this ticket (2022-02-19)

To Reproduce:
1. Start projectMSDL
2. Wait while it plays through a few songs
3. Observe seizure screen

Workaround:
While pressing "N" to go to the next visual does not fix this, pressing "R" does seem to fix the issue.

**Comment by kblaschke** [comment] 2022-06-25 14:05
"R" and "N" hotkeys internally to the exact same thing, loading another preset. Besides using a different playlist index, there's no code difference loading presets on either command.

If you still experience these rendering issues, please supply more information:

- Which GPU are you running projectM on?
- Which drivers are used to render it?

In addition to that, you could run it with [RenderDoc](https://renderdoc.org/) and see if there are any error messages if you capture a broken frame.

**Comment by kblaschke** [comment] 2022-11-21 20:50
No further information was provided within months. I'll close this issue for now, as I cannot reproduce it without the requested data.

If this issue is still present, please answer the questions above and reopen.

**Closed by kblaschke** 2022-11-21 20:50 UTC
Labels: need more information
